#!/usr/bin/env bash
#install your load balancer

sudo apt-get -y install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 5773-webs
    bind *:80
    mode http
    balance roundrobin
    server 5773-web01 54.197.31.204:80 check
    server 5773-web-02 54.147.183.28:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
